version: '3'

services:
  fileServer:
    build: .
    ports:
      - "3001:3001"
    volumes:
      - ./:/app
    command: bash -c "npm i && npm run build && npm run start:prod"
  mysql:
    image: mysql:8
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio_storage:/data
    environment:
      MINIO_ROOT_USER: MINIOADMIN
      MINIO_ROOT_PASSWORD: MINIOADMIN
    command: server --console-address ":9001" /data

  core:
    build: .
    image: palphone-core
    container_name: palphone-core
    networks:
      - core
    restart: always
    entrypoint: [ "/bin/palphone-core", "serve", "--migrate" ]
    ports:
      - "8095:8080"
      - "8099:8099"
    volumes:
      - ./storage/statics:/app/statics
      - ./logs/:/logs/
    environment:
      MYSQL_HOST: palphone_mariadb
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - "mysql"
      - "redis"
      - "nats"

  mariadb:
    image: mariadb:10.4.13
    volumes:
      - core-mariadb-storage:/var/lib/mysql
    restart: always
    hostname: mariadb
    container_name: palphone_mariadb
    networks:
      - core
    environment:
      MYSQL_USER: palphone_user
      MYSQL_PASSWORD: palphone_pass
      MYSQL_DATABASE: palphone
      MYSQL_ROOT_PASSWORD: root
    command: mysqld --lower_case_table_names=1 --skip-ssl
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --explicit_defaults_for_timestamp
  redis:
     image: bitnami/redis:6.2
     hostname: redis
     container_name: palphone_redis
     networks:
       - core
     volumes:
       - ./storage/redis:/data
     environment:
       - ALLOW_EMPTY_PASSWORD=yes
  nats:
     image: nats:2.6.5-alpine3.14
     hostname: nats
     container_name: palphone_nats
     networks:
       - core
     command: nats-server --jetstream

volumes:
  core-mariadb-storage:

networks:
  core:
    external: true